## Percptron model - Learning purposes only

In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.datasets import load_digits


##Yann lecun

In [2]:
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [3]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [4]:
digits['target']

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
x = digits.data
y = digits.target

#This is a multi class classification problem

In [9]:
print(x.shape)
print(y.shape)

(1797, 64)
(1797,)


In [8]:
#Split the data into train and test

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

In [ ]:
#x = x/255.0

In [10]:
# Building Perceptron modesl
#Scaling is required.
from sklearn.linear_model import Perceptron

perceptron_model = Perceptron()
perceptron_model.fit(x_train, y_train)

Perceptron()

In [12]:
print("What is the training accuracy of perceptron model")
print(perceptron_model.score(x_train, y_train))

print("What is the test accuracy of perceptron model")
print(perceptron_model.score(x_test, y_test))

perceptron_train = perceptron_model.predict(x_train)
perceptron_test = perceptron_model.predict(x_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Training accuracy", accuracy_score(y_train, perceptron_train))
print("Test accuracy",accuracy_score(y_test, perceptron_test))

print("Classification report Train")
print(classification_report(y_train, perceptron_train))
print("Classification report Test")
print(classification_report(y_test, perceptron_test))

What is the training accuracy of perceptron model
0.9762435040831478
What is the test accuracy of perceptron model
0.9688888888888889
Training accuracy 0.9762435040831478
Test accuracy 0.9688888888888889
Classification report Train
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       125
           1       0.95      0.99      0.97       140
           2       0.98      1.00      0.99       136
           3       0.98      0.98      0.98       131
           4       1.00      0.99      1.00       134
           5       0.93      1.00      0.97       143
           6       0.98      0.99      0.98       138
           7       0.98      1.00      0.99       131
           8       1.00      0.85      0.92       137
           9       0.99      0.97      0.98       132

    accuracy                           0.98      1347
   macro avg       0.98      0.98      0.98      1347
weighted avg       0.98      0.98      0.98      1347

Classific

## Regression problem

In [42]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout, BatchNormalization

In [43]:
data = pd.read_csv('/Users/pawankumarkc/Documents/vscode_workspace/MLAlgo/datasets/boston.csv')
data.head()

CRIM    ZN  INDUS  CHAS     NX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [44]:
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NX         0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [45]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

x.head()

CRIM    ZN  INDUS  CHAS     NX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [46]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [47]:
## Feature scaling - mandatory step
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x = sc.fit_transform(x)
pd.DataFrame(x).head()

0         1         2         3         4         5         6   \
0 -0.419782  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1 -0.417339 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2 -0.417342 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3 -0.416750 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4 -0.412482 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   

         7         8         9         10        11        12  
0  0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1  0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2  0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3  1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4  1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501

# Building multilayer perceptron - DNN


In [48]:
# Building multilayer perceptron - DNN
dnn = Sequential()
#Add hidden layer 1
dnn.add(Dense( 8, activation='relu', input_dim=13))
#Batch normalisation
dnn.add(BatchNormalization())
#Dropout
dnn.add(Dropout(0.25))
# Add one more hidden layer
dnn.add(Dense( 8, activation='relu'))
dnn.add(BatchNormalization())
dnn.add(Dropout(0.25))
#output
dnn.add(Dense( 1, activation='linear'))

dnn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 8)                 112       
                                                                 
 batch_normalization_7 (Bat  (None, 8)                 32        
 chNormalization)                                                
                                                                 
 dropout_4 (Dropout)         (None, 8)                 0         
                                                                 
 dense_16 (Dense)            (None, 8)                 72        
                                                                 
 batch_normalization_8 (Bat  (None, 8)                 32        
 chNormalization)                                                
                                                                 
 dropout_5 (Dropout)         (None, 8)                

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=101)

In [52]:
# Compile the model using optimization and loss function

dnn.compile(optimizer='sgd', loss='mean_squared_error')

#Fit the model
history  = dnn.fit(x_train, y_train, epochs=500)

Epoch 1/500
13/13 [==============================] - 0s 953us/step - loss: 223.5708
Epoch 2/500
13/13 [==============================] - 0s 821us/step - loss: 55.7314
Epoch 3/500
13/13 [==============================] - 0s 756us/step - loss: 54.1714
Epoch 4/500
13/13 [==============================] - 0s 757us/step - loss: 42.1476
Epoch 5/500
13/13 [==============================] - 0s 764us/step - loss: 38.4628
Epoch 6/500
13/13 [==============================] - 0s 703us/step - loss: 52.7815
Epoch 7/500
13/13 [==============================] - 0s 765us/step - loss: 46.1692
Epoch 8/500
13/13 [==============================] - 0s 719us/step - loss: 34.6946
Epoch 9/500
13/13 [==============================] - 0s 653us/step - loss: 49.0181
Epoch 10/500
13/13 [==============================] - 0s 700us/step - loss: 39.9993
Epoch 11/500
13/13 [==============================] - 0s 693us/step - loss: 40.2602
Epoch 12/500
13/13 [==============================] - 0s 667us/step - loss: 40.7350


In [53]:
# Prediction test dataset

y_pred = dnn.predict(x_test)
y_pred

4/4 [==============================] - 0s 878us/step


array([[39.953587],
       [28.01849 ],
       [16.315443],
       [16.2546  ],
       [28.190153],
       [31.993155],
       [42.53808 ],
       [15.675387],
       [30.997267],
       [11.721943],
       [26.33406 ],
       [16.394615],
       [20.534714],
       [20.6008  ],
       [22.732105],
       [21.438168],
       [13.10594 ],
       [31.315285],
       [24.019064],
       [23.149508],
       [14.306598],
       [21.511045],
       [20.306618],
       [28.090092],
       [33.195065],
       [17.583504],
       [26.667679],
       [18.175224],
       [29.608643],
       [29.892221],
       [21.061934],
       [19.445288],
       [35.60364 ],
       [40.648666],
       [25.691408],
       [21.515598],
       [15.579539],
       [17.67213 ],
       [10.472805],
       [25.72641 ],
       [21.392735],
       [21.449715],
       [36.31484 ],
       [15.788514],
       [19.68529 ],
       [21.543459],
       [28.748755],
       [17.318542],
       [23.290022],
       [21.584982],


In [54]:
print(y_pred[0:10])
print('************************')
print(y_test[0:10])


[[39.953587]
 [28.01849 ]
 [16.315443]
 [16.2546  ]
 [28.190153]
 [31.993155]
 [42.53808 ]
 [15.675387]
 [30.997267]
 [11.721943]]
************************
195    50.0
4      36.2
434    11.7
458    14.9
39     30.8
304    36.1
225    50.0
32     13.2
157    41.3
404     8.5
Name: MEDV, dtype: float64


In [55]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.767267324555694
