In [1]:
import numpy as np
num_inputs = 4

In [3]:
# OR gate/data
input_array = np.array( [[0,0], [1,0], [0,1], [1,1]] )
input_array

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [4]:
output_array = np.array([0,1,1,1])

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [6]:
#Model defn

classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=1, activation='sigmoid'))
#Bias is added by default

classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])
classifier.fit(input_array, output_array, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 116ms/step - loss: 0.4179 - accuracy: 1.0000
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4006 - accuracy: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3866 - accuracy: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3750 - accuracy: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 0.3652 - accuracy: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 0.3567 - accuracy: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 0.3491 - accuracy: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 3ms/step - loss: 0.3423 - accuracy: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3361 - accuracy: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.3304 - accuracy: 0.7500
Epoch 11/100
1/1 [=========

In [8]:
#Model predication and validation
y_pred = classifier.predict(input_array)
y_pred = (y_pred>0.5)
y_pred

1/1 [==============================] - 0s 33ms/step


array([[False],
       [ True],
       [ True],
       [ True]])

In [9]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred, output_array))

1.0


### We see that after just few epoc's the models accuracy is 100%, which means it is able to classify all the points correctly. 

## Precptron network for XOR data

In [10]:
input_array = np.array( [[0,0], [0,1], [1,0], [1,1]] )
input_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [11]:
output_array = np.array([0,1,1,0])

In [12]:
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=1, activation='sigmoid'))
#Bias is added by default

classifier.summary()
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])
classifier.fit(input_array, output_array, epochs=100)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Epoch 1/100
1/1 [==============================] - 0s 101ms/step - loss: 0.7055 - accuracy: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.7020 - accuracy: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6997 - accuracy: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6982 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6971 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6964 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6959 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6956 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6953 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6951 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

In [13]:
y_pred = classifier.predict(input_array)
y_pred = (y_pred>0.5)
y_pred

1/1 [==============================] - 0s 18ms/step


array([[False],
       [ True],
       [False],
       [ True]])

In [14]:
print(accuracy_score(y_pred, output_array))

0.5


### We see that after 100 few epoc's the models accuracy is 50%, which means it is not able to classify all the points correctly. The model is not able to segrigate the classes correctly (Misclassified)

### Multilayer percptron for XOR

In [ ]:
input_array = np.array( [[0,0], [0,1], [1,0], [1,1]] )
input_array
output_array = np.array([0,1,1,0])

In [15]:
classifier = Sequential()
classifier.add(Dense(input_shape=(2,), units=10, activation='relu'))
classifier.add(Dense(units=1, activation='sigmoid'))
#Bias is added by default

classifier.summary()
classifier.compile(optimizer=SGD(learning_rate=0.5), loss='binary_crossentropy', metrics=['accuracy'])
classifier.fit(input_array, output_array, epochs=100)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10)                30        
                                                                 
 dense_3 (Dense)             (None, 1)                 11        
                                                                 
Total params: 41 (164.00 Byte)
Trainable params: 41 (164.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Epoch 1/100
1/1 [==============================] - 0s 109ms/step - loss: 0.7160 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.2500
Epoch 3/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6786 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6684 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6597 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6534 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6479 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6473 - accuracy: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6387 - accuracy: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6357 - accuracy: 0.7500
Epoch 11/100
1/1 [=========

In [17]:

y_pred = classifier.predict(input_array)
y_pred = (y_pred>0.5)
y_pred
print(accuracy_score(y_pred, output_array))

1/1 [==============================] - 0s 25ms/step
1.0
